import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'

import InputDate from '@/components/input-date'
import InputGeneral from '@/components/input-general'
import InputBooker from '@/components/input-booker'
import InputSeat from '@/components/input-seat'
import NavigationLinks from '@/components/navigation-links'
import NavigationLinks1 from '@/components/navigation-links1'


export default function Home() {
  return (
    <>
      <div className="home-container">
        <Head>
          <title>Trippy - Travel</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/logoblack.ico" />
        </Head>
        <header data-role="Header" className="home-header">
          <Image
            alt="logo"
            src="/playground_assets/logo%20black.svg"
            className="home-image"
            width={109}
            height={66}
            
          />
          <div className="home-nav"></div>
          <div className="home-btn-group">
            
            <button className="home-login button">
            <Link
            href='/sign-in-page'
            >Sign in</Link>
            </button>
            <button className="home-register button">
            <Link
            href='/sign-up-page'
            >Sign up</Link>
            </button>
          </div>
          <div data-role="BurgerMenu" className="home-burger-menu">
            <svg viewBox="0 0 1024 1024" className="home-icon">
              <path d="M128 554.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667zM128 298.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667zM128 810.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667z"></path>
            </svg>
          </div>
          <div data-role="MobileMenu" className="home-mobile-menu">
            <div className="home-nav1">
              <div className="home-container1">
                <img
                  alt="image"
                  src="https://presentation-website-assets.teleporthq.io/logos/logo.png"
                  className="home-image1"
                />
                <div data-role="CloseMobileMenu" className="home-menu-close">
                  <svg viewBox="0 0 1024 1024" className="home-icon02">
                    <path d="M810 274l-238 238 238 238-60 60-238-238-238 238-60-60 238-238-238-238 60-60 238 238 238-238z"></path>
                  </svg>
                </div>
              </div>
              <NavigationLinks rootClassName="navigation-links-root-class-name8"></NavigationLinks>
            </div>
          </div>
        </header>
        <div className="home-hero">
          <div className="home-container2">
            <h1 className="home-text">Experience your</h1>
            <h1 className="home-text1">Travel with us</h1>
            <span className="home-text2">
              We have more than 1 million happy customer arround the world
            </span>
          </div>
        </div>
        <div className='booker'>
          <h2 className='booker-information'>Booker Information</h2>
          <form>
            <InputBooker
            text='Title'
            label='Email'
            label1='Name'
            label2='Phone'
            ></InputBooker>

          </form>
        </div>
        <div className='booker1'>
          <h2 className='booker-information1'>1 - Dewasa #1 </h2>
          <form>
          
          </form>
        </div>
      </div>

      <style jsx>
        {`
          .home-container {
            width: 100%;
            display: flex;
            overflow: auto;
            min-height: 100vh;
            align-items: center;
            flex-direction: column;
          }
          .booker-information {
            margin-left: 90px;
            margin-top: 30px;
            font-size: ;
          }
          .booker-information1 {
            margin-left: 90px;
            margin-top: 30px;
            font-size: ;
          }
          .home-header {
            width: 100%;
            display: flex;
            z-index: 100;
            align-items: center;
            padding-top: var(--dl-space-space-unit);
            padding-left: var(--dl-space-space-threeunits);
            padding-right: var(--dl-space-space-threeunits);
            padding-bottom: var(--dl-space-space-unit);
            justify-content: space-between;
          }
          .home-image {
            width: 109px;
            height: 66px;
          }
          .home-nav {
            border: 2px dashed rgba(120, 120, 120, 0.4);
            display: flex;
          }
          .home-btn-group {
            display: flex;
            align-items: center;
            flex-direction: row;
            justify-content: space-between;
          }
          .home-login {
            color: #ffffff;
            width: 108px;
            height: 44px;
            font-style: normal;
            transition: 0.3s;
            font-family: Montserrat;
            font-weight: 600;
            border-color: #ffffff;
            border-width: 1px;
            margin-right: var(--dl-space-space-twounits);
            border-radius: 13px;
            background-color: rgba(255, 255, 255, 0);
          }
          .home-login:hover {
            cursor: pointer;
            background: rgba(62, 92, 184, 0.44);
            border-color: rgba(62, 92, 184, 0.44);
          }
          .home-register {
            color: #ffffff;
            width: 108px;
            height: 44px;
            font-style: normal;
            transition: 0.3s;
            font-family: Montserrat;
            font-weight: 600;
            border-color: #ffffff;
            border-width: 0px;
            border-radius: 13px;
            background-color: #3e5cb8;
          }
          .home-register:hover {
            cursor: pointer;
            background: rgba(62, 92, 184, 0.44);
            border-color: rgba(62, 92, 184, 0.44);
          }
          .home-burger-menu {
            display: none;
          }
          .home-icon {
            width: var(--dl-size-size-xsmall);
            height: var(--dl-size-size-xsmall);
          }
          .home-mobile-menu {
            top: 0px;
            left: 0px;
            width: 100%;
            height: 100vh;
            display: none;
            padding: 32px;
            z-index: 100;
            position: absolute;
            flex-direction: column;
            justify-content: space-between;
            background-color: #fff;
          }
          .home-nav1 {
            display: flex;
            align-items: flex-start;
            flex-direction: column;
          }
          .home-container1 {
            width: 100%;
            display: flex;
            align-items: center;
            margin-bottom: var(--dl-space-space-threeunits);
            justify-content: space-between;
          }
          .home-image1 {
            height: 2rem;
          }
          .home-menu-close {
            display: flex;
            align-items: center;
            justify-content: center;
          }
          .home-icon02 {
            width: var(--dl-size-size-xsmall);
            height: var(--dl-size-size-xsmall);
          }
          .home-hero {
            top: 0px;
            left: 0px;
            width: 100%;
            filter: blur(0.5px);
            display: flex;
            padding: var(--dl-space-space-threeunits);
            z-index: 96;
            position: absolute;
            min-height: 80vh;
            align-items: center;
            flex-direction: column;
            background-size: cover;
            justify-content: center;
            background-image: url('/playground_assets/wp9247941-4k-indonesia-wallpapers-1500h.jpg');
          }
          .home-hero:hover {
            border-color: rgba(62, 92, 184, 0.44);
          }
          .home-container2 {
            top: 429px;
            left: 558px;
            display: flex;
            position: absolute;
            align-items: center;
            flex-direction: column;
            justify-content: center;
          }
          .home-text {
            color: var(--dl-color-gray-white);
            font-size: 2rem;
            font-style: normal;
            font-family: Montserrat;
            font-weight: 700;
            text-shadow: 2px 6px 4px rgba(0, 0, 0, 0.25);
          }
          .home-text1 {
            color: var(--dl-color-gray-white);
            font-size: 48px;
            font-style: normal;
            margin-top: var(--dl-space-space-halfunit);
            font-family: Montserrat;
            font-weight: 700;
            text-shadow: 2px 6px 4px rgba(0, 0, 0, 0.25);
          }
          .home-text2 {
            color: var(--dl-color-gray-white);
            font-size: 24px;
            font-style: normal;
            margin-top: var(--dl-space-space-unit);
            font-family: Montserrat;
            font-weight: 700;
            text-shadow: 2px 6px 4px rgba(0, 0, 0, 0.25);
            margin-bottom: var(--dl-space-space-unit);
          }
          .booker {
            top: 697px;
            flex: 0 0 auto;
            left: 190px;
            width: 80%;
            height: auto;
            margin: auto;
            display: flex;
            z-index: 100;
            position: absolute;
            align-items: flex-start;
            border-color: #a7a7a7;
            border-style: solid;
            border-width: 1px;
            border-radius: 13px;
            flex-direction: column;
            justify-content: flex-start;
            background-color: #ffffff;
          }
          .booker1 {
            top: 1300px;
            flex: 0 0 auto;
            left: 190px;
            width: 80%;
            height: auto;
            margin: auto;
            display: flex;
            z-index: 100;
            position: absolute;
            align-items: flex-start;
            border-color: #a7a7a7;
            border-style: solid;
            border-width: 1px;
            border-radius: 13px;
            flex-direction: column;
            justify-content: flex-start;
            background-color: #ffffff;
          }
          .home-container4 {
            gap: var(--dl-space-space-twounits);
            flex: 0 0 auto;
            width: auto;
            height: auto;
            display: flex;
            align-self: center;
            margin-top: var(--dl-space-space-oneandhalfunits);
            align-items: flex-start;
            margin-left: auto;
            margin-right: auto;
          }
          .home-container5 {
            display: flex;
            align-items: flex-start;
          }
          .home-icon04 {
            width: 32px;
            height: 32px;
            transform: rotate(45deg);
            align-self: center;
          }
          .home-text3 {
            align-self: center;
            font-style: normal;
            font-family: Montserrat;
            font-weight: 600;
            padding-left: var(--dl-space-space-halfunit);
            padding-right: var(--dl-space-space-halfunit);
          }
          .home-container6 {
            display: flex;
            align-items: flex-start;
          }
          .home-icon07 {
            width: 32px;
            height: 32px;
            align-self: center;
          }
          .home-text4 {
            align-self: center;
            font-style: normal;
            font-family: Montserrat;
            font-weight: 600;
            padding-left: var(--dl-space-space-halfunit);
            padding-right: var(--dl-space-space-halfunit);
          }
          .home-group-input-top {
            gap: var(--dl-space-space-oneandhalfunits);
            flex: 0 0 auto;
            width: auto;
            height: 100px;
            display: flex;
            margin-top: var(--dl-space-space-oneandhalfunits);
            align-items: center;
            margin-left: auto;
            margin-right: auto;
            margin-bottom: var(--dl-space-space-oneandhalfunits);
            justify-content: center;
          }
          .home-group-input-bot {
            gap: var(--dl-space-space-oneandhalfunits);
            flex: 0 0 auto;
            width: auto;
            height: 100px;
            display: flex;
            margin-top: var(--dl-space-space-oneandhalfunits);
            align-items: center;
            margin-left: auto;
            margin-right: auto;
            margin-bottom: var(--dl-space-space-oneandhalfunits);
            justify-content: center;
          }
          .home-container7 {
            width: 675px;
            display: flex;
            align-items: center;
            padding-top: var(--dl-space-space-unit);
            border-width: 0px;
            padding-bottom: var(--dl-space-space-unit);
            justify-content: center;
            background-color: #3e5cb8;
          }
          .home-icon09 {
            fill: #ffffff;
            width: 24px;
            height: 24px;
          }
          .home-text5 {
            color: #ffffff;
            font-style: normal;
            font-family: Montserrat;
            font-weight: 600;
            padding-left: var(--dl-space-space-halfunit);
            padding-right: var(--dl-space-space-halfunit);
          }
          @media (max-width: 991px) {
            .home-hero {
              flex-direction: column;
            }
            .home-text {
              text-align: center;
            }
            .home-text1 {
              text-align: center;
            }
            .home-text2 {
              text-align: center;
            }
          }
          @media (max-width: 767px) {
            .home-header {
              padding-left: var(--dl-space-space-twounits);
              padding-right: var(--dl-space-space-twounits);
            }
            .home-nav {
              display: none;
            }
            .home-btn-group {
              display: none;
            }
            .home-burger-menu {
              display: flex;
              align-items: center;
              justify-content: center;
            }
            .home-mobile-menu {
              display: none;
            }
            .home-hero {
              padding-left: var(--dl-space-space-twounits);
              padding-right: var(--dl-space-space-twounits);
            }
          }
          @media (max-width: 479px) {
            .home-header {
              padding: var(--dl-space-space-unit);
            }
            .home-image {
              width: 93px;
              height: 44px;
            }
            .home-btn-group {
              display: none;
            }
            .home-mobile-menu {
              display: none;
              padding: 16px;
            }
            .home-hero {
              width: 100%;
              padding: var(--dl-space-space-twounits);
              padding-top: var(--dl-space-space-twounits);
              padding-left: var(--dl-space-space-unit);
              padding-right: var(--dl-space-space-unit);
            }
          }
        `}
      </style>
    </>
  )
}
