import Head from 'next/head'
import Image from 'next/image'

export default function home() {
    return (
        <>
            <div className='home-container'>
            <Head>
                <title>Trippy - Travel</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logoblack.ico" />
            </Head>
            </div>
        </>
    )

}