import Head from 'next/head'
import React from 'react'
import Layouts from '@/components/Layouts';
import Navtabs from '@/components/NavTabs';
import Image from 'next/image';
import { BsCalendarDate, BsSearch, BsCalendar4Event, BsBookmarkCheck, BsCheckSquare } from "react-icons/bs";

const Index = () => {
  return (
    <>
        <Head>
            <title>Trippy - Flight</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layouts>
            <section className=' relative sm:mb-[250px] mb-[450px]'>
                <div className='h-[80vh] header'>
                    <div className='bg-cover brightness-[0.85] w-full h-full absolute top-[-80px]' style={{ backgroundImage: 'url("/playground_assets/wp9247941-4k-indonesia-wallpapers-1500h.jpg")', zIndex: '-2' }}></div>
                    <div className='flex flex-col justify-center h-full items-center text-white z-10 text-center'>
                        <h2 className='font-medium md:text-4xl text-2xl mb-4'>Experience Your</h2>
                        <h1 className='font-bold md:text-6xl text-4xl mb-6' >Best Trip With Us</h1>
                        <p className='md:text-xl text-lg'>We have more than 1 million happy customer arround the world</p>
                    </div>
                    <div className='flex justify-center'>
                        <div className='border-2 rounded-xl shadow-md bg-[#fff] absolute sm:bottom-[-140px] bottom-[-400px] px-10 py-3 mx-5 lg:min-w-[800px]'>
                            <div className='flex justify-center my-2'>
                                <Navtabs/>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section className='bg-[#dce2e5] mt-20'>
                <div className='container mx-auto py-20 px-10'>
                    <div className='block sm:flex justify-between items-center mt-7 text-center sm:text-start'>
                        <h1 className='text-5xl font-bold text-[#232730] leading-[60px]'>Travel to make memories <br/> all arround world</h1>
                    </div>
                    <div className='sm:grid block lg:grid-cols-3 grid-cols-2 gap-x-5 gap-y-5 mt-10 justify-items-center max-w-[1300px] mx-auto'>
                        <div className='col-span-1 bg-[#fff]  flex justify-center items-center text-center rounded-3xl p-10 shadow-lg max-w-[400px]'>
                            <div>
                                <div className="flex justify-center">
                                    <div className="flex justify-center bg-[#3e5cb8] text-white p-10 rounded-full ">
                                        <BsCalendarDate className='text-5xl'/>
                                    </div>
                                </div>
                                <h1 className="font-medium font-sans text-2xl mt-8">BOX & RELAX</h1>
                                <p className=" mt-3">We realize ideas from simple to complex,every become easy to use</p>
                            </div>
                        </div>
                        <div className='col-span-1 bg-[#fff]  flex justify-center items-center text-center rounded-3xl p-10 shadow-lg max-w-[400px]'>
                            <div>
                                <div className="flex justify-center">
                                    <div className="flex justify-center bg-[#3e5cb8] text-white p-10 rounded-full ">
                                        <BsCheckSquare className='text-5xl'/>
                                    </div>
                                </div>
                                <h1 className="font-medium font-sans text-2xl mt-8">SMART CHECKLIST</h1>
                                <p className=" mt-3">We realize ideas from simple to complex,every become easy to use</p>
                            </div>
                        </div>
                        <div className='col-span-1 bg-[#fff]  flex justify-center items-center text-center rounded-3xl p-10 shadow-lg max-w-[400px]'>
                            <div>
                                <div className="flex justify-center">
                                    <div className="flex justify-center bg-[#3e5cb8] text-white p-10 rounded-full ">
                                        <BsBookmarkCheck className='text-5xl'/>
                                    </div>
                                </div>
                                <h1 className="font-medium font-sans text-2xl mt-8">SAVE MORE</h1>
                                <p className=" mt-3">We realize ideas from simple to complex,every become easy to use</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section className='my-20'>
            <div className="container mx-auto px-10">
          <h1 className="text-center text-4xl font-semibold text-[#232730] mb-12">Why Flight Ticket</h1>
          <div className="grid lg:grid-cols-4 grid-cols-2 mt-20 gap-y-20 justify-items-center">
            <div className="col-span-1 text-center max-w-[300px]">
              <div className=" flex justify-center max-h-[140px]">
                <Image src='/playground_assets/promotion_1.png' alt='' width={162} height={162} className="" />
              </div>
              <h1 className="text-lg font-semibold mt-10 text-[#59595b]">Hassle-Free</h1>
              <p className="mt-3 text-[#b4b4b7]">Make a transaction from anywhere at any time, from desktop, mobile app, or mobile web. </p>
            </div>
            <div className="col-span-1 text-center max-w-[300px]">
              <div className=" flex justify-center  max-h-[140px]">
                <Image src='/playground_assets/promotion_2.png' alt='' width={203} height={141} className="" />
              </div>
              <h1 className="text-lg font-semibold mt-10 text-[#59595b]">Service You Can Trust</h1>
              <p className="mt-3 text-[#b4b4b7]">You get what you paid for – guaranteed.</p>
            </div>
            <div className="col-span-1 text-center max-w-[300px]">
              <div className=" flex justify-center  max-h-[140px]">
                <Image src='/playground_assets/promotion_3.png' alt='' width={157} height={171} className="" />
              </div>
              <h1 className="text-lg font-semibold mt-10 text-[#59595b]">Various Payment Options</h1>
              <p className="mt-3 text-[#b4b4b7]">Be more flexible with various payment methods from ATM, Bank Transfer, Credit Card, and Internet Banking, to Cash.</p>
            </div>
            <div className="col-span-1 text-center max-w-[300px]">
              <div className=" flex justify-center  max-h-[140px]">
                <Image src='/playground_assets/promotion_4.png' alt='' width={199} height={157} className="" />
              </div>
              <h1 className="text-lg font-semibold mt-10 text-[#59595b]">Secure Transaction Guaranteed</h1>
              <p className="mt-3 text-[#b4b4b7]">Security and privacy of your online transaction are protected by RapidSSL authorized technology. Receive instant confirmation and e-ticket or voucher directly in your email.</p>
            </div>
          </div>
        </div>
            </section>
        </Layouts>
    </>
  )
}

export default Index