import Head from 'next/head'
import Image from 'next/image'

import NavigationLinks from '@/components/navigation-links'
import InputGeneral from '@/components/input-general'
import InputDate from '@/components/input-date'
import InputSeat from '@/components/input-seat'
import InputPassenger from '@/components/input-passenger'

import { Inter, Montserrat } from 'next/font/google'
import projectStyles from './mainglobal.css'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })
const montesrrat = Montserrat({ subsets: ['latin']})

const Home = (props) => {
  return (
    <div className={styles['container']}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header data-role="Header" className={styles['header']}>
        <img
          alt="logo"
          src="/playground_assets/logo%20black.svg"
          className={styles['image']}
        />
        <div className={styles['nav']}></div>
        <div className={styles['btn-group']}>
          <button className={` ${styles['login']} ${projectStyles['button']} `}>
            Sign in
          </button>
          <button
            className={` ${styles['register']} ${projectStyles['button']} `}
          >
            Sign up
          </button>
        </div>
        <div data-role="BurgerMenu" className={styles['burger-menu']}>
          <svg viewBox="0 0 1024 1024" className={styles['icon']}>
            <path d="M128 554.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667zM128 298.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667zM128 810.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667z"></path>
          </svg>
        </div>
        <div data-role="MobileMenu" className={styles['mobile-menu']}>
          <div className={styles['nav1']}>
            <div className={styles['container1']}>
              <img
                alt="image"
                src="https://presentation-website-assets.teleporthq.io/logos/logo.png"
                className={styles['image1']}
              />
              <div data-role="CloseMobileMenu" className={styles['menu-close']}>
                <svg viewBox="0 0 1024 1024" className={styles['icon02']}>
                  <path d="M810 274l-238 238 238 238-60 60-238-238-238 238-60-60 238-238-238-238 60-60 238 238 238-238z"></path>
                </svg>
              </div>
            </div>
            <NavigationLinks rootClassName="root-class-name8"></NavigationLinks>
          </div>
        </div>
      </header>
      <div className={styles['hero']}>
        <div className={styles['container2']}>
          <h1 className={styles['text']}>Experience your</h1>
          <h1 className={styles['text1']}>Travel with us</h1>
          <span className={styles['text2']}>
            We have more than 1 million happy customer arround the world
          </span>
        </div>
      </div>
      <div className={styles['container3']}>
        <div className={styles['container4']}>
          <div className={styles['container5']}>
            <svg viewBox="0 0 1024 1024" className={styles['icon04']}>
              <path d="M895.488 528.896l-212.821-121.643v-204.587c0-82.347-66.987-149.333-149.333-149.333s-149.333 66.987-149.333 149.333v204.587l-212.821 121.643c-56.192 32.085-79.573 101.163-54.443 160.811 25.131 59.691 90.965 91.093 153.131 73.387l114.133-32.64v35.755l-37.291 29.824c-51.115 40.917-63.147 113.792-27.861 168.917 35.285 55.168 106.411 74.795 165.077 45.483 0.171-0.043 21.333-7.808 49.408-7.808s49.237 7.765 49.408 7.808c58.667 29.312 129.792 9.685 165.077-45.483 35.285-55.125 23.253-128-27.861-168.917l-37.291-29.824v-35.755l114.176 32.64c62.165 17.707 128-13.696 153.131-73.387 25.131-59.691 1.749-128.725-54.485-160.811zM871.339 656.555c-8.405 19.883-30.336 30.421-51.029 24.448l-222.976-63.659v189.909l69.333 55.467c17.024 13.611 21.035 37.931 9.301 56.32-11.733 18.347-35.328 24.875-55.040 15.147-0.341-0.171-35.157-16.853-87.595-16.853s-87.253 16.683-87.595 16.853c-19.712 9.685-43.307 3.157-55.040-15.147-11.733-18.389-7.765-42.667 9.301-56.32l69.333-55.467v-189.909l-222.976 63.701c-20.693 5.973-42.624-4.565-51.029-24.448-8.363-19.883-0.597-42.88 18.176-53.589l255.829-146.219v-254.123c0-35.285 28.715-64 64-64s64 28.715 64 64v254.123l255.829 146.176c18.773 10.709 26.539 33.707 18.176 53.589z"></path>
              <path d="M554.667 192c0 11.782-9.551 21.333-21.333 21.333-11.782 0-21.333-9.551-21.333-21.333 0-11.782 9.551-21.333 21.333-21.333 11.782 0 21.333 9.551 21.333 21.333z"></path>
            </svg>
            <span className={styles['text3']}>Flights</span>
          </div>
          <div className={styles['container6']}>
            <svg viewBox="0 0 1024 1024" className={styles['icon07']}>
              <path d="M256 512v128h512v-128h-512zM342 298v128h128v-128h-128zM682 426v-128h-128v128h128zM854 512v214h-58l-28 84h-42l-28-84h-370l-30 84h-42l-28-84h-58v-214q0-34 26-60t60-26v-128q0-34 26-59t60-25h340q34 0 60 25t26 59v128q34 0 60 26t26 60z"></path>
            </svg>
            <span className={styles['text4']}>Rooms</span>
          </div>
        </div>
        <div className={styles['group-input-top']}>
          <InputGeneral></InputGeneral>
          <InputGeneral
            text="Arrival City"
            image_src="/playground_assets/arrival%20city%20icon2.svg"
            textinput_placeholder="Where are you going..."
          ></InputGeneral>
          <InputDate
            text="Departure Date"
            image_src="/playground_assets/calender%20depature.svg"
            rootClassName="root-class-name"
            textinput_placeholder="When you want go"
          ></InputDate>
          <InputDate
            text="Arrival Date"
            image_src="/playground_assets/calender%20depature.svg"
            rootClassName="root-class-name1"
          ></InputDate>
        </div>
        <div className={styles['group-input-bot']}>
          <InputSeat
            text="Seat Class"
            image_src="/playground_assets/circle%20icon.svg"
            rootClassName="root-class-name"
          ></InputSeat>
          <InputPassenger
            text="Passenger"
            image_src="/playground_assets/circle%20icon2.svg"
            rootClassName="root-class-name"
            textinput_placeholder="Passengers"
          ></InputPassenger>
          <div
            className={` ${styles['container7']} ${projectStyles['button']} `}
          >
            <svg
              viewBox="0 0 950.8571428571428 1024"
              className={styles['icon09']}
            >
              <path d="M658.286 475.429c0-141.143-114.857-256-256-256s-256 114.857-256 256 114.857 256 256 256 256-114.857 256-256zM950.857 950.857c0 40-33.143 73.143-73.143 73.143-19.429 0-38.286-8-51.429-21.714l-196-195.429c-66.857 46.286-146.857 70.857-228 70.857-222.286 0-402.286-180-402.286-402.286s180-402.286 402.286-402.286 402.286 180 402.286 402.286c0 81.143-24.571 161.143-70.857 228l196 196c13.143 13.143 21.143 32 21.143 51.429z"></path>
            </svg>
            <span className={styles['text5']}>Search</span>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Home;