import Head from 'next/head'
import React from 'react'
import LayoutsBg from '@/components/LayoutsBg'
import Navtabs from '@/components/NavTabs'
import Image from 'next/image';
import { BsCalendarDate, BsSearch, BsCalendar4Event, BsBookmarkCheck, BsCheckSquare } from "react-icons/bs";
import { MdFlightClass } from 'react-icons/md'
import { TbPlaneInflight } from 'react-icons/tb'
import { IoAirplaneOutline } from "react-icons/io5";
import { RiSuitcaseLine } from 'react-icons/ri'

const Flight = () => {
    const flights = [
        {
            id: 1,
            plane: 'Garuda Indonesia',
            orderNum: 24508,
            classType: 'Economy Class',
            depatureCity: 'Jakarta',
            depatureTime: '11:00',
            arrivalCity: 'Aceh',
            arrivalTime: '13:00',
            price: '2.200.000,00',
            weight: 25,
        },
        {
            id: 2,
            plane: 'Lion Air',
            orderNum: 24509,
            classType: 'Economy Class',
            depatureCity: 'Jakarta',
            depatureTime: '11:00',
            arrivalCity: 'Medan',
            arrivalTime: '12:00',
            price: '1.800.000,00',
            weight: 25,
        },
        {
            id: 3,
            plane: 'Batik Air',
            orderNum: 24510,
            classType: 'Economy Class',
            depatureCity: 'Jakarta',
            depatureTime: '11:00',
            arrivalCity: 'Balikpapan',
            arrivalTime: '12:00',
            price: '1.000.000,00',
            weight: 25,
        },
        {
            id: 4,
            plane: 'Garuda Indonesia',
            orderNum: 24511,
            classType: 'Economy Class',
            depatureCity: 'Medan',
            depatureTime: '09:00',
            arrivalCity: 'Bali',
            arrivalTime: '12:00',
            price: '2.800.000,00',
            weight: 25,
        },
        {
            id: 5,
            plane: 'Citilink',
            orderNum: 24512,
            classType: 'Economy Class',
            depatureCity: 'Bali',
            depatureTime: '13:00',
            arrivalCity: 'Samarinda',
            arrivalTime: '15:10',
            price: '1.900.000,00',
            weight: 25,
        },
        {
            id: 6,
            plane: 'Lion Air',
            orderNum: 24513,
            classType: 'Economy Class',
            depatureCity: 'Aceh',
            depatureTime: '08:00',
            arrivalCity: 'Balikpapan',
            arrivalTime: '11:00',
            price: '2.700.000,00',
            weight: 25,
        },

    ]
  return (
    <>
        <Head>
            <title>Search - Flight</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <LayoutsBg>
        <section className='mt-10'>
                <div className='container mx-auto py-2'>
                    {flights.map((item) => {
                        return(
                            <div key={item.id} className='border-2 rounded-xl shadow-md bg-[#fff] px-10 py-3 my-4'>
                            <div className='flex justify-center my-2'>
                                <div className='w-full flex flex-col py-4 sm:px-0 mx-auto'>
                                            <div className='flex flex-col gap-y-8 justify-center'>
                                        <div className='flex justify-between items-center'>
                                            <span className='flex items-center text-2xl gap-2 font-semibold'>
                                                <TbPlaneInflight className='text-3xl'/> {item.plane}
                                            </span>
                                            <span className='text-2xl font-semibold'>{item.orderNum}</span>
                                            <span className='flex items-center text-2xl gap-2 font-semibold text-[#7A7C85]'>
                                                <MdFlightClass className='text-3xl text-black'/> {item.classType}
                                            </span>
                                        </div>
                                        <div className='flex justify-between items-center'>
                                            <div className='flex items-center'>
                                                <div className='flex flex-col items-center'>
                                                    <h1 className='font-bold text-3xl'>{item.depatureTime}</h1>
                                                    <h3 className='text-base'>{item.depatureCity}</h3>
                                                </div>
                                                <div className="lg:flex grid items-center mx-5">
                                                    <div className="max-w-[50px] xl:min-w-[100px] h-0.5 bg-[#7d7d7f] mx-auto px-10"></div>
                                                    <IoAirplaneOutline className="mx-2 text-[#7d7d7f] text-3xl" />
                                                    <div className="max-w-[50px] xl:min-w-[100px] h-0.5 bg-[#7d7d7f] mx-auto px-10"></div>
                                                </div>
                                                <div className='flex flex-col'>
                                                    <h1 className='font-bold text-3xl'>{item.arrivalTime}</h1>
                                                    <h3 className='text-base'>{item.arrivalCity}</h3>
                                                </div>
                                            </div>
                                            <h1 className='text-2xl font-bold'>{item.price}<span className='text-sm font-medium'>/pax</span></h1>
                                        </div>
                                        <div className='flex justify-between items-center'>
                                        <span className='flex items-center text-2xl gap-2 font-semibold'>
                                                <RiSuitcaseLine className='text-1xl'/> {item.weight} kg
                                            </span>

                                            <button className='bg-[#3E5CB8] px-4 py-2 rounded-md text-white text-base font-medium'>Choose Flight</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        )
                    })}
                </div>
        </section>
        </LayoutsBg>
    </>
  )
}

export default Flight

{/* <section className=' relative sm:mb-[350px] mb-[450px]'>
                <div className='h-[80vh] header'>
                    <div className='bg-cover brightness-[0.85] w-full h-full absolute top-[-80px]' style={{ backgroundImage: 'url("/playground_assets/wp9247941-4k-indonesia-wallpapers-1500h.jpg")', zIndex: '-2' }}></div>
                    <div className='flex flex-col justify-center h-full items-center text-white z-10 text-center'>
                        <h2 className='font-medium md:text-4xl text-2xl mb-4'>Experience Your</h2>
                        <h1 className='font-bold md:text-6xl text-4xl mb-6' >Best Trip With Us</h1>
                        <p className='md:text-xl text-lg'>We have more than 1 million happy customer arround the world</p>
                    </div>
                    <div className='flex justify-center'>
                        <div className='border-2 rounded-xl shadow-md bg-[#fff] absolute sm:bottom-[-1200px] bottom-[-400px] px-10 py-3 mx-5 lg:min-w-[800px]'>
                            <div className='flex justify-center my-2'>
                                <div className='w-full flex flex-col py-4 sm:px-0 mx-auto'>
                                    
                                    {flights.map((item) => {
                                        return(
                                            <div key={item.id                                               } className='flex flex-col gap-y-8 justify-center'>
                                        <div className='flex justify-between items-center'>
                                            <span className='flex items-center text-2xl gap-2 font-semibold'>
                                                <TbPlaneInflight className='text-3xl'/> Garuda Indonesia
                                            </span>
                                            <span className='text-2xl font-semibold'>25045</span>
                                            <span className='flex items-center text-2xl gap-2 font-semibold text-[#7A7C85]'>
                                                <MdFlightClass className='text-3xl text-black'/> Economy Class
                                            </span>
                                        </div>
                                        <div className='flex justify-between items-center'>
                                            <div className='flex items-center'>
                                                <div className='flex flex-col items-center'>
                                                    <h1 className='font-bold text-3xl'>11:00</h1>
                                                    <h3 className='text-base'>Jakarta</h3>
                                                </div>
                                                <div className="lg:flex grid items-center mx-5">
                                                    <div className="max-w-[50px] xl:min-w-[100px] h-0.5 bg-[#7d7d7f] mx-auto px-10"></div>
                                                    <IoAirplaneOutline className="mx-2 text-[#7d7d7f] text-3xl" />
                                                    <div className="max-w-[50px] xl:min-w-[100px] h-0.5 bg-[#7d7d7f] mx-auto px-10"></div>
                                                </div>
                                                <div className='flex flex-col'>
                                                    <h1 className='font-bold text-3xl'>11:00</h1>
                                                    <h3 className='text-base'>Jakarta</h3>
                                                </div>
                                            </div>
                                            <h1 className='text-2xl font-bold'>Rp 250.000,00<span className='text-sm font-medium'>/pax</span></h1>
                                        </div>
                                        <div className='flex justify-between items-center'>
                                        <span className='flex items-center text-2xl gap-2 font-semibold'>
                                                <RiSuitcaseLine className='text-1xl'/> 25 kg
                                            </span>

                                            <button className='bg-[#3E5CB8] px-4 py-2 rounded-md text-white text-base font-medium'>Choose Flight</button>
                                        </div>
                                    </div>
                                        )
                                    })}
                                    

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section> */}