import Head from 'next/head'
import { MdLogout } from 'react-icons/md'
import { useRouter } from 'next/router'
const AdminDash = () => {
    const router  = useRouter()
    const handleLogut = () => {
        localStorage.clear()
        router.push('/sign-in')

    }

  return (
    <div>
        <Head>
            <title>Dash - Admin</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <header className='bg-[#333] text-[#fff] p-[20px] text-center'>
            <h1>Admin Dashboard</h1>
        </header>
        <aside className='bg-[#f1f1f1] h-full fixed w-[200px]'> 
        <nav>
            <ul className=' list-none p-0'>
                <li className=' p-[10px]'><a className='text-[#333] block no-underline' href="#">Flight</a></li>
                <li className=' p-[10px]'><a className='text-[#333] block no-underline' href="#">Hotel</a></li>
                <li className=' p-[10px]'><a className='text-[#333] block no-underline' href="#">User</a></li>
                <li className=' p-[10px]'><a className='text-[#333] block no-underline' href="#">Balance</a></li>
            </ul>
            <button onClick={handleLogut} className='ml-2 p-2 border border-solid border-black flex items-center'>
                <MdLogout className='mx-1'/>
                Log Out</button>
        </nav>
        </aside>
        <main className='ml-[200px] p-[20px]'>
            <h2>Dashboard</h2>
            <div className="flex flex-wrap">
                <div className="bg-[#f1f1f1] border border-solid border-[#ccc] m-[10px] p-[20px] w-[300px]">
                    <h3 className='mt-0'>Users</h3>
                    <p>100</p>
                </div>
                <div className="bg-[#f1f1f1] border border-solid border-[#ccc] m-[10px] p-[20px] w-[300px]">
                    <h3 className='mt-0'>Orders</h3>
                    <p>50</p>
                </div>
            </div>
        </main>
        
    {/* <footer className='bg-[#000]'>
      <p>Copyright © 2023</p>
    </footer> */}
    </div>
  )
}

export default AdminDash

// export const getServerSideProps = async () => {
//     const user = localStorage.getItem('user')
//     const res = await axios.get(`https://petstore.swagger.io/v2/user/${user.fullName}`)
//     return {
//         props: {
//             valid: res.data
//         }
//     }
// }