import Head from 'next/head'
import { MdLogout } from 'react-icons/md'
import { useRouter } from 'next/router'
import { useState } from 'react'
import tbstyles from '@/styles/Table.module.scss'


const MitraDash = () => {
    const router  = useRouter()
    const handleLogut = () => {
        localStorage.clear()
        router.push('/sign-in')
    }

    const[flight, setFlight] = useState(false)
    const[hotel, setHotel] = useState(false)
    const[user, setUser] = useState(false)
    const[balance, setBalance] = useState(false)

    const a1 = () => {
        setFlight(true)
        setHotel(false)
        setUser(false)
        setBalance(false)
    }

    const a2 = () => {
        setFlight(false)
        setHotel(true)
        setUser(false)
        setBalance(false)
    }

    const a3 = () => {
        setFlight(false)
        setHotel(false)
        setUser(true)
        setBalance(false)
    }

    const a4 = () => {
        setFlight(false)
        setHotel(false)
        setUser(false)
        setBalance(true)
    }

  return (
    <div>
    <Head>
        <title>Dash - Mitra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <header className='bg-[#333] text-[#fff] p-[20px] text-center'>
        <h1>Mitra Dashboard</h1>
    </header>
    <aside className='bg-[#f1f1f1] h-full fixed w-[200px]'> 
        <nav>
            <ul className=' list-none p-0'>
                <li className=' p-[10px]'><a className='text-[#333] block no-underline' onClick={a1}>Flight</a></li>
                <li className=' p-[10px]'><a className='text-[#333] block no-underline' onClick={a2}>Hotel</a></li>
                <li className=' p-[10px]'><a className='text-[#333] block no-underline' onClick={a3}>User</a></li>
                <li className=' p-[10px]'><a className='text-[#333] block no-underline' onClick={a4}>Balance</a></li>
            </ul>
            <button onClick={handleLogut} className='ml-2 p-2 border border-solid border-black flex items-center'>
                <MdLogout className='mx-1'/>
                Log Out</button>
        </nav>
    </aside>
    <main className='ml-[200px] p-[20px]'>
        {flight ? 
        <>
        <h2>Flight Table</h2>
        <table className={tbstyles.table}>
        <thead>
            <tr>
                <th>Depature - Arrival</th>
                <th>Flight Time</th>
                <th>Type</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Bali - Medan</td>
                <td>1 Hour</td>
                <td>Economy</td>
            </tr>
            <tr>
                <td>Medan - Jakarta</td>
                <td>1 Hour 30 Minuets</td>
                <td>Economy</td>
            </tr>
            <tr>
                <td>Yogyakarta - Balikpapan</td>
                <td>1 Hour</td>
                <td>Economy</td>
            </tr>
            <tr>
                <td>Jakarta - Aceh</td>
                <td>2 Hour 15 Minuets</td>
                <td>Economy</td>
            </tr>
        </tbody>
    </table>
        {/* <div className="flex flex-wrap">
            <div className="bg-[#f1f1f1] border border-solid border-[#ccc] m-[10px] p-[20px] w-[300px]">
                <h3 className='mt-0'>Users</h3>
                <p>100</p>
            </div>
            <div className="bg-[#f1f1f1] border border-solid border-[#ccc] m-[10px] p-[20px] w-[300px]">
                <h3 className='mt-0'>Orders</h3>
                <p>50</p>
            </div>
        </div> */}
        </> 
        : ""}

{hotel ? 
        <>
        <h2>Hotel Table</h2>
        <table className={tbstyles.table}>
        <thead>
            <tr>
                <th>Name</th>
                <th>Age</th>
                <th>Country</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>John</td>
                <td>25</td>
                <td>USA</td>
            </tr>
            <tr>
                <td>Jane</td>
                <td>30</td>
                <td>Canada</td>
            </tr>
            <tr>
                <td>Bob</td>
                <td>20</td>
                <td>Australia</td>
            </tr>
        </tbody>
    </table>
        </> 
        : ""}

{user ? 
        <>
        <h2>User Table</h2>
        <table className={tbstyles.table}>
        <thead>
            <tr>
                <th>Name</th>
                <th>Age</th>
                <th>Country</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>John</td>
                <td>25</td>
                <td>USA</td>
            </tr>
            <tr>
                <td>Jane</td>
                <td>30</td>
                <td>Canada</td>
            </tr>
            <tr>
                <td>Bob</td>
                <td>20</td>
                <td>Australia</td>
            </tr>
        </tbody>
    </table>
        </> 
        : ""}

{balance ? 
        <>
        <h2>Balance</h2>
        <table className={tbstyles.table}>
        <thead>
            <tr>
                <th>Name</th>
                <th>Age</th>
                <th>Country</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>John</td>
                <td>25</td>
                <td>USA</td>
            </tr>
            <tr>
                <td>Jane</td>
                <td>30</td>
                <td>Canada</td>
            </tr>
            <tr>
                <td>Bob</td>
                <td>20</td>
                <td>Australia</td>
            </tr>
        </tbody>
    </table>
        </> 
        : ""}
    </main>
    
{/* <footer className='bg-[#000]'>
  <p>Copyright © 2023</p>
</footer> */}
</div>
  )
}

export default MitraDash

{/* <h2>Dashboard</h2>
        <div className="flex flex-wrap">
            <div className="bg-[#f1f1f1] border border-solid border-[#ccc] m-[10px] p-[20px] w-[300px]">
                <h3 className='mt-0'>Users</h3>
                <p>100</p>
            </div>
            <div className="bg-[#f1f1f1] border border-solid border-[#ccc] m-[10px] p-[20px] w-[300px]">
                <h3 className='mt-0'>Orders</h3>
                <p>50</p>
            </div>
        </div> */}